services:
  - type: web
    name: personal-projects
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
